import type { Lang } from "./types.ts";
export type { Lang };

type Dict = Record<string, string>;

const en: Dict = {
  appName: "AniList Recommender",
  tagline: "Anime picks from your own list — explained.",
  usernameLabel: "AniList username",
  go: "Get recommendations",
  loadingProfile: "Reading your list…",
  loadingRecos: "Building recommendations… (first run ~1 min, then cached)",
  errUserNotFound: "User not found on AniList. Check the spelling.",
  errAnilistDown: "AniList is unreachable right now. Try again in a bit.",
  errGeneric: "Something went wrong. Try again.",
  yourTaste: "Your taste profile",
  loved: "You love",
  disliked: "You avoid",
  confidenceLow: "few scored entries — profile is rough",
  completed: "Completed",
  dropped: "Dropped",
  paused: "Paused",
  current: "Watching",
  planning: "Planning",
  meanScore: "Mean score",
  recommendations: "Recommendations",
  gemsOnly: "Hidden gems only",
  sortFinal: "Best match",
  sortGem: "Best gem",
  sortAffinity: "Pure taste",
  allFormats: "All formats",
  avoidThese: "Maybe avoid these",
  llmOn: "LLM explanations: on",
  llmOff: "LLM explanations: off (local model not reachable)",
  emptyState: "Nothing to recommend — try a username with more scored entries.",
  affinity: "taste",
  quality: "quality",
  community: "community",
  badgeNextStep: "Next step",
  badgeEntryPoint: "Start here",
  badgeHiddenGem: "Hidden gem",
  badgeSpinOff: "Spin-off",
  moreInSeries: "{n} more in this series",
  whyBase: "Matches your taste for {dims}{studioPart}.{examplesPart}{gemPart}",
  whyNeutral: "Rated {avg}/100 on AniList by {pop} members.{gemPart}",
  whyExamples: " Seen in: {examples}.",
  whyGem: " Hidden gem: only {pop} members, {avg}/100 on AniList.",
  whyNotBase: "Shares {dims} you dropped or rated low{examplesPart}{droppedPart}.",
  whyNotExamples: " (e.g. {examples})",
  whyNotDropped: ", and you dropped {title} in this series",
  dimTag: "tags",
  dimGenre: "genres",
  dimStudio: "studio",
  dimEra: "era",
  langToggle: "Italiano",
  viewRecos: "Recommendations",
  viewGems: "Hidden gems",
  apiHint: "Everything runs locally: your list is read from AniList, explanations come from your own LLM server.",
  setupTitle: "Welcome — one-time setup",
  setupIntro: "Pick and download a local LLM to power the explanations. Recommended based on this machine:",
  hwOs: "Operating system",
  hwChip: "Processor",
  hwRam: "RAM",
  recModel: "Recommended model",
  mlxOpt: "Apple MLX variant",
  mlxWarn: "Requires the PrismML fork of MLX (not merged upstream yet) — not automated. Command to run it:",
  installCli: "Install LM Studio CLI (one click)",
  installingCli: "Installing LM Studio CLI…",
  backendMissing: "LM Studio CLI not found on this machine.",
  winFirstRun: "On Windows, open the LM Studio app once after install, then retry.",
  download: "Download model",
  downloading: "Downloading model…",
  downloadDone: "Model downloaded.",
  downloadFailed: "Download failed — check the log below.",
  skipDownload: "Skip download (I'll use an existing model)",
  useCustom: "Use a custom OpenAI-compatible endpoint instead",
  customUrl: "Endpoint URL (e.g. http://127.0.0.1:11434/v1)",
  customUse: "Use this endpoint",
  skipSetup: "Skip setup (no LLM explanations)",
  finishTitle: "All set!",
  llmStarting: "Starting the LLM backend…",
  llmReady: "LLM backend is up.",
  llmOffNote: "LLM backend did not start — the app works fine without it. Check data/llm.log.",
  startUsing: "Enter the app",
  osMac: "macOS",
  osWin: "Windows",
  osLinux: "Linux",
  backendOmlx: "oMLX (Apple Silicon)",
  backendLms: "LM Studio",
  omlxFound: "oMLX detected — models on disk:",
  omlxStartNote: "The oMLX server will be started automatically.",
};

const it: Dict = {
  appName: "AniList Recommender",
  tagline: "Anime consigliati dalla tua lista — con spiegazione.",
  usernameLabel: "Username AniList",
  go: "Consigliami",
  loadingProfile: "Leggo la tua lista…",
  loadingRecos: "Costruisco i consigli… (prima volta ~1 min, poi cache)",
  errUserNotFound: "Utente non trovato su AniList. Controlla la grafia.",
  errAnilistDown: "AniList non raggiungibile al momento. Riprova tra poco.",
  errGeneric: "Qualcosa è andato storto. Riprova.",
  yourTaste: "Il tuo profilo di gusto",
  loved: "Ami",
  disliked: "Eviti",
  confidenceLow: "pochi voti — profilo approssimativo",
  completed: "Completati",
  dropped: "Dropped",
  paused: "In pausa",
  current: "In corso",
  planning: "In piano",
  meanScore: "Voto medio",
  recommendations: "Consigli",
  gemsOnly: "Solo gemme nascoste",
  sortFinal: "Miglior match",
  sortGem: "Miglior gemma",
  sortAffinity: "Puro gusto",
  allFormats: "Tutti i formati",
  avoidThese: "Forse da evitare",
  llmOn: "Spiegazioni LLM: attive",
  llmOff: "Spiegazioni LLM: offline (modello locale non raggiungibile)",
  emptyState: "Niente da consigliare — prova uno username con più voti.",
  affinity: "gusto",
  quality: "qualità",
  community: "community",
  badgeNextStep: "Prossimo passo",
  badgeEntryPoint: "Inizia da qui",
  badgeHiddenGem: "Gemma nascosta",
  badgeSpinOff: "Spin-off",
  moreInSeries: "altri {n} della serie",
  whyBase: "Matcha il tuo gusto per {dims}{studioPart}.{examplesPart}{gemPart}",
  whyNeutral: "Valutato {avg}/100 su AniList da {pop} membri.{gemPart}",
  whyExamples: " Visto in: {examples}.",
  whyGem: " Gemma nascosta: solo {pop} membri, {avg}/100 su AniList.",
  whyNotBase: "Condivide {dims} che hai droppato o votato basso{examplesPart}{droppedPart}.",
  whyNotExamples: " (es. {examples})",
  whyNotDropped: ", e in questa serie hai droppato {title}",
  dimTag: "tag",
  dimGenre: "generi",
  dimStudio: "studio",
  dimEra: "epoca",
  langToggle: "English",
  viewRecos: "Consigli",
  viewGems: "Gemme nascoste",
  apiHint: "Tutto in locale: la lista arriva da AniList, le spiegazioni dal tuo server LLM.",
  setupTitle: "Benvenuto — configurazione una tantum",
  setupIntro: "Scegli e scarica un LLM locale per le spiegazioni. Consigliato in base a questa macchina:",
  hwOs: "Sistema operativo",
  hwChip: "Processore",
  hwRam: "RAM",
  recModel: "Modello consigliato",
  mlxOpt: "Variante Apple MLX",
  mlxWarn: "Richiede il fork PrismML di MLX (non ancora mergiato upstream) — non automatizzato. Comando per usarlo:",
  installCli: "Installa LM Studio CLI (un click)",
  installingCli: "Installo la LM Studio CLI…",
  backendMissing: "CLI di LM Studio non trovata su questa macchina.",
  winFirstRun: "Su Windows, apri una volta l'app LM Studio dopo l'installazione, poi riprova.",
  download: "Scarica modello",
  downloading: "Scarico il modello…",
  downloadDone: "Modello scaricato.",
  downloadFailed: "Download fallito — controlla il log qui sotto.",
  skipDownload: "Salta il download (userò un modello già presente)",
  useCustom: "Usa invece un endpoint OpenAI-compatibile custom",
  customUrl: "URL endpoint (es. http://127.0.0.1:11434/v1)",
  customUse: "Usa questo endpoint",
  skipSetup: "Salta la configurazione (niente spiegazioni LLM)",
  finishTitle: "Tutto pronto!",
  llmStarting: "Avvio il backend LLM…",
  llmReady: "Backend LLM attivo.",
  llmOffNote: "Il backend LLM non si è avviato — l'app funziona lo stesso. Vedi data/llm.log.",
  startUsing: "Entra nell'app",
  osMac: "macOS",
  osWin: "Windows",
  osLinux: "Linux",
  backendOmlx: "oMLX (Apple Silicon)",
  backendLms: "LM Studio",
  omlxFound: "oMLX rilevato — modelli su disco:",
  omlxStartNote: "Il server oMLX verrà avviato automaticamente.",
};

const DICTS: Record<Lang, Dict> = { en, it };

/** Format a template with {placeholders}. */
export function tr(lang: Lang, key: string, params?: Record<string, string | number>): string {
  let s = DICTS[lang][key] ?? DICTS.en[key] ?? key;
  if (params) for (const [k, v] of Object.entries(params)) s = s.replaceAll(`{${k}}`, String(v));
  return s;
}
